#Suppression des SNPs unique de chaque matrice
# 10 bed matrices : http://genostats.ovh/Simon/
#Telechargement de la liste des SNPs en commun dans les 10 bed matrices ;
#tinyurl.com/4kejpf5e

listeSNP <- read.table('listeSNP.txt')
listeSNP <- listeSNP$V1
require(gaston)
x <- read.bed.matrix('structure01')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure01')
x <- read.bed.matrix('structure02')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure02')
x <- read.bed.matrix('structure03')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure03')
x <- read.bed.matrix('structure04')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure04')
x <- read.bed.matrix('structure05')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure05')
x <- read.bed.matrix('structure06')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure06')
x <- read.bed.matrix('structure07')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure07')
x <- read.bed.matrix('structure08')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure08')
x <- read.bed.matrix('structure09')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure09')
x <- read.bed.matrix('structure10')
x <- select.snps(x, x@snps$id %in% listeSNP == TRUE)
gc()
write.bed.matrix(x, 'structure10')

